### ISSUE TITLE
Fails to run on server

### ISSUE THREAD

**Issue by VaelophisNyx** [teamauroramods/EnhancedMushrooms-Fabric#2]
21.04 21:18:25 [Server] main/FATAL Mixin prepare failed preparing MixinBoatEntityRenderer in enhanced_mushrooms.mixins.json: org.spongepowered.asm.mixin.transformer.throwables.InvalidMixinException Cannot load class com.github.teamaurora.enhanced_mushrooms.mixin.MixinBoatEntityRenderer in environment type SERVER

**Comment by campbebj** [comment]
same thing here.


Mixin prepare failed preparing MixinBoatEntityRenderer in enhanced_mushrooms.mixins.json: org.spongepowered.asm.mixin.transformer.throwables.InvalidMixinException Cannot load class com.github.teamaurora.enhanced_mushrooms.mixin.MixinBoatEntityRenderer in environment type SERVER
--
org.spongepowered.asm.mixin.transformer.throwables.InvalidMixinException: Cannot load class com.github.teamaurora.enhanced_mushrooms.mixin.MixinBoatEntityRenderer in environment type SERVER


Caused by: java.lang.RuntimeException: Cannot load class com.github.teamaurora.enhanced_mushrooms.mixin.MixinBoatEntityRenderer in environment type SERVER

**Comment by JustinPlayzz** [comment]
This is a known issues, sorry for the inconvenience

**Comment by JustinPlayzz** [comment]
@GalacticRuler @campbebj the issue has been fixed
